CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS news_items (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), headline TEXT NOT NULL, summary TEXT, source TEXT NOT NULL, source_id TEXT, url TEXT UNIQUE NOT NULL, published_at TIMESTAMPTZ NOT NULL, image_url TEXT, teams TEXT[] DEFAULT '{}', sentiment_score NUMERIC, sentiment_label TEXT CHECK (sentiment_label IN ('positive', 'neutral', 'negative')), sentiment_breakdown JSONB, sentiment_source TEXT, sentiment_comment_count INTEGER DEFAULT 0, sentiment_analyzed_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_news_items_url ON news_items(url);
CREATE INDEX IF NOT EXISTS idx_news_items_published ON news_items(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_items_teams ON news_items USING GIN(teams);
CREATE TABLE IF NOT EXISTS polls (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), question TEXT NOT NULL, options JSONB NOT NULL DEFAULT '[]', event_context TEXT, active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_polls_active ON polls(active) WHERE active = TRUE;
CREATE TABLE IF NOT EXISTS poll_responses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), poll_id UUID NOT NULL REFERENCES polls(id) ON DELETE CASCADE, option_index INTEGER NOT NULL, ip_address TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(poll_id, ip_address));
CREATE INDEX IF NOT EXISTS idx_poll_responses_lookup ON poll_responses(poll_id, ip_address);
ALTER TABLE news_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_responses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "News items are viewable by everyone" ON news_items FOR SELECT USING (true);
CREATE POLICY "News items are insertable by service role" ON news_items FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "News items are updatable by service role" ON news_items FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Polls are viewable by everyone" ON polls FOR SELECT USING (true);
CREATE POLICY "Polls are insertable by service role" ON polls FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Polls are updatable by service role" ON polls FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Poll responses are insertable by service role" ON poll_responses FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Poll responses are viewable by service role" ON poll_responses FOR SELECT USING (auth.role() = 'service_role');
INSERT INTO polls (question, options, event_context, active) VALUES ('Who wins the 2025-26 NBA MVP?', '[{"text":"Shai Gilgeous-Alexander","votes":0},{"text":"Cade Cunningham","votes":0},{"text":"Nikola Jokic","votes":0},{"text":"Victor Wembanyama","votes":0}]'::jsonb, '2025-26 NBA MVP Race', true);
INSERT INTO polls (question, options, event_context, active) VALUES ('Who wins 2025-26 Rookie of the Year?', '[{"text":"Cooper Flagg","votes":0},{"text":"Ace Bailey","votes":0},{"text":"Dylan Harper","votes":0},{"text":"Kon Knueppel","votes":0},{"text":"Someone else","votes":0}]'::jsonb, '2025-26 Rookie of the Year', true);
INSERT INTO polls (question, options, event_context, active) VALUES ('Are the Detroit Pistons a legitimate championship contender?', '[{"text":"Yes, they are for real","votes":0},{"text":"No, they will fold in the playoffs","votes":0},{"text":"Ask me in April","votes":0}]'::jsonb, '2025-26 Pistons Contender Debate', true);
INSERT INTO polls (question, options, event_context, active) VALUES ('Who finishes as the 2 seed in the West?', '[{"text":"Oklahoma City Thunder","votes":0},{"text":"San Antonio Spurs","votes":0},{"text":"Denver Nuggets","votes":0},{"text":"Houston Rockets","votes":0},{"text":"Minnesota Timberwolves","votes":0}]'::jsonb, '2025-26 Western Conference Race', true);
CREATE OR REPLACE FUNCTION cleanup_old_news() RETURNS void AS $$ BEGIN DELETE FROM news_items WHERE created_at < NOW() - INTERVAL '7 days'; END; $$ LANGUAGE plpgsql;
CREATE TABLE IF NOT EXISTS article_comments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), article_url TEXT NOT NULL REFERENCES news_items(url) ON DELETE CASCADE, comment_text TEXT NOT NULL, author_name TEXT NOT NULL DEFAULT 'Anonymous', published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), like_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_article_comments_url ON article_comments(article_url);
CREATE INDEX IF NOT EXISTS idx_article_comments_likes ON article_comments(article_url, like_count DESC);
ALTER TABLE article_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Article comments are viewable by everyone" ON article_comments FOR SELECT USING (true);
CREATE POLICY "Article comments are insertable by service role" ON article_comments FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Article comments are deletable by service role" ON article_comments FOR DELETE USING (auth.role() = 'service_role');
